### ISSUE TITLE
Fatal error processing large XML (990+ messages) files

### ISSUE THREAD

**Issue by ivancarlosti** [gutmensch/docker-dmarc-report#60]
Hi team, please, there is any way to fix this issue? It opens fine files with ~750 messages, it starts to fail when I try to open XML with 990 messages.

The error displayed is:

`Fatal error: Uncaught ValueError: DOMDocument::loadXML(): Argument #1 ($source) must not be empty in /var/www/viewer/dmarcts-report-viewer-report-data.php:218 Stack trace: #0 /var/www/viewer/dmarcts-report-viewer-report-data.php(218): DOMDocument->loadXML() #1 /var/www/viewer/dmarcts-report-viewer-report-data.php(59): formatXML() #2 /var/www/viewer/dmarcts-report-viewer-report-data.php(371): tmpl_reportData() #3 {main} thrown in /var/www/viewer/dmarcts-report-viewer-report-data.php on line 218`

There is any workaround I can implement here?

Thanks a lot and regards

**Comment by ivancarlosti** [comment]
Solved using - "PARSER_XML_MAXSIZE=500000" environment :)
